const nodemailer = require('nodemailer');

const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

const reportContent = `📰 Daily Report — ${today}
================================================================

🌍 GEOPOLITICS: US-IRAN WAR (Day 20)
• US forces striking military targets deep inside Iran; Israel struck the South Pars gas field
• Oil prices surging — major energy impact globally  
• Trump: "Not putting US troops on the ground in Iran"
Sources:
  - CNN: https://www.cnn.com/2026/03/19/middleeast/us-israel-iran-middle-east-war-day-20-what-we-know-intl-hnk
  - Al Jazeera: https://www.aljazeera.com/video/newsfeed/2026/3/20/unpacking-netanyahus-latest-claims-about-the-war-on-iran
  - Fox News: https://www.foxnews.com/video/6391246686112
  - TODAY: https://www.today.com/video/trump-says-he-s-not-putting-us-troops-on-the-ground-in-iran-259646533987

🤖 AI & TECHNOLOGY
• AI infrastructure expanding — Cerebras on AWS, NVIDIA open data initiatives
• New AI models releasing March 2026; startups benefiting from improved infrastructure
Sources:
  - Mean CEO: https://blog.mean.ceo/new-ai-model-releases-news-march-2026/
  - Radical Data Science: https://radicaldatascience.wordpress.com/2026/03/17/ai-news-briefs-bulletin-board-for-march-2026/
  - Tech Startups: https://techstartups.com/2026/03/18/top-tech-news-today-march-18-2026/

🇺🇸 US POLITICS
• Trump met with international leaders March 20; issued new executive orders on Iran
• Attended a casualty return ceremony; Iran war central to second term agenda
Sources:
  - CNN: https://www.cnn.com/politics/president-donald-trump-47
  - AP News: https://apnews.com/hub/donald-trump
  - White House: https://www.whitehouse.gov/videos/president-trump-participates-in-a-bilateral-meeting-mar-19-2026/
  - Federal Register: https://www.federalregister.gov/presidential-documents/executive-orders/donald-trump/2026

💰 MARKETS & ECONOMY
• Dow +200pts; S&P 500 rose on March 20 amid Iran war volatility
• S&P 500 had posted new year low earlier due to Iran oil crisis
• Oil prices remain elevated; Nvidia key for Wall Street outlook
• Global 15% tariff initiative in effect — market volatility persists
Sources:
  - CNBC: https://www.cnbc.com/2026/03/03/stock-market-today-live-updates.html
  - CNBC: https://www.cnbc.com/2026/03/12/stock-market-today-live-updates.html
  - CNBC: https://www.cnbc.com/2026/03/13/stock-market-next-week-outlook-for-march-16-20-2026.html

================================================================
Generated by OpenClaw Agent | Powered by Tavily Search API
`;

async function main() {
  console.log('=== Daily Report Email Test ===');
  console.log('Date:', today);
  console.log('');

  const envPath = 'C:\\Program Files\\QClaw\\resources\\openclaw\\config\\skills\\imap-smtp-email\\.env';
  const fs = require('fs');

  if (!fs.existsSync(envPath)) {
    console.log('STATUS: SMTP not configured (no .env file)');
    console.log('');
    console.log('=== REPORT ===');
    console.log(reportContent);
    return;
  }

  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  const env = {};
  lines.forEach(l => {
    const idx = l.indexOf('=');
    if (idx > 0 && !l.trim().startsWith('#')) {
      env[l.substring(0, idx).trim()] = l.substring(idx+1).trim();
    }
  });

  console.log('SMTP_HOST:', env.SMTP_HOST || 'NOT SET');
  console.log('SMTP_USER:', env.SMTP_USER ? 'SET' : 'NOT SET');
  console.log('SMTP_PASS:', env.SMTP_PASS ? 'SET' : 'NOT SET');

  if (!env.SMTP_HOST || !env.SMTP_USER || !env.SMTP_PASS) {
    console.log('');
    console.log('=== REPORT (SMTP not ready) ===');
    console.log(reportContent);
    return;
  }

  try {
    const transporter = nodemailer.createTransport({
      host: env.SMTP_HOST,
      port: parseInt(env.SMTP_PORT) || 587,
      secure: env.SMTP_SECURE === 'true',
      auth: { user: env.SMTP_USER, pass: env.SMTP_PASS },
      tls: { rejectUnauthorized: false }
    });

    await transporter.verify();
    console.log('\nSMTP verified! Sending...');

    const info = await transporter.sendMail({
      from: env.SMTP_FROM || env.SMTP_USER,
      to: 'HZ-lu2007@outlook.com',
      subject: `Daily Report - ${today}`,
      text: reportContent.trim()
    });

    console.log('Email sent! ID:', info.messageId);
  } catch(err) {
    console.log('Failed:', err.message);
    console.log('');
    console.log('=== REPORT ===');
    console.log(reportContent);
  }
}

main();
