import smtplib, ssl, sys

HOST, PORT = 'smtp.163.com', 465
USER, PASS, FROM = 'kimberagent@163.com', 'KUy32yx8YxKiQww7', 'kimberagent@163.com'
TO = 'HZ-lu2007@outlook.com'

report = """工作日报 - 2026年3月20日
================================================================

【今日通信内容概要】

本次会话为 Agent（Kim）首次上线运行，主要围绕以下议题展开：
- Agent 身份初始化（BOOTSTRAP 流程）
- Tavily Search API 接入与测试
- 邮件发送能力搭建
- 工作规则制定

【已完成工作任务】

1. Agent 初始化配置
   - 完成 BOOTSTRAP.md 流程，建立 Agent 身份
   - 配置工作规则：任务队列机制、自主优先级、卡住跳转、每10分钟进度报告

2. Tavily Search API 接入
   - 收到并验证 API Key（tvly-dev-cUiFs-xxx）
   - api.tavily.com 测试连通 ✅
   - 英文新闻搜索 ✅ / 中文内容搜索 ✅ / 深度搜索 ✅
   - 创建 tavily-search skill 至 workspace ✅
   - 搜索主题测试：JD Vance 对2026年美伊战争立场（25个国际来源）

3. 邮件发送能力搭建
   - 确认目标邮箱：HZ-lu2007@outlook.com
   - 收集 163 邮箱 SMTP 凭据（kimberagent@163.com）
   - 解决 nodemailer 缺失问题，改用 Python smtplib 直连发送
   - 成功发送日报邮件至 Outlook ✅

4. 其他已验证能力
   - QClaw 主程序运行正常 ✅
   - 飞书 IM 通信正常 ✅
   - Windows 系统代理状态检查完成
   - API Key 已记录至 memory/apikeys.md

【未完成 / 阻塞项】

- 公邮平台通道（本地代理19000不通，暂无法使用）
- SMTP 凭据未能持久化写入 skill 配置（权限限制，Program Files 目录写入需管理员权限）
- 建议后续：将 SMTP 配置写入用户目录或 workspace 目录，避免权限问题

【当前队列状态】

已清空（今日任务全部完成）

================================================================
Generated by OpenClaw Agent | 2026-03-20
"""

try:
    ctx = ssl.create_default_context()
    s = smtplib.SMTP_SSL(HOST, PORT, context=ctx)
    s.login(USER, PASS)
    msg = f'From: {FROM}\r\nTo: {TO}\r\nSubject: \u5de5\u4f5c\u65e5\u62a5 - 2026\u5e743\u670820\u65e5\r\n\r\n{report}'
    s.sendmail(FROM, [TO], msg.encode('utf-8'))
    s.quit()
    print('SENT: Work report email sent!')
except Exception as e:
    print(f'FAILED: {e}', file=sys.stderr)
    sys.exit(1)
